<a href="https://colab.research.google.com/github/punramon/bsc_dpdm24/blob/main/Chapter_3_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.chdir('/content/drive/MyDrive/bsc_dpdm24_data')

!pwd # เช็ค path ที่กำลังทำงานอยู่

/content/drive/MyDrive/bsc_dpdm24_data

In [4]:
unit_type_data = pd.read_csv("/content/drive/MyDrive/bsc_dpdm24_data/opendata_unittype.csv")


# Data exploration

* 'project_id' --> เชื่อมกับรายละเอียดโครงการ

In [ ]:
unit_type_data

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,4441,unittype_11075,project_3853,4 Bedroom,2,Condo,คอนโด,NaN,250.0,50200000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:56,2020-10-14 00:57:57,baania,https://baania.com/th/project/โดมัส-16-3853/4-...,2023-08-31
1,28021,unittype_18174,project_7334,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,132.0,3666666.0,...,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:37:28,2020-10-14 00:43:47,baania,https://baania.com/th/project/บ้านเมฆธารา-2-73...,2023-08-31
2,14541,unittype_35595,project_15267,1 Bedroom,2,Condo,คอนโด,NaN,45.0,3250000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:30,2020-10-14 00:55:24,baania,https://baania.com/th/project/เดอะ-เซสท์-ลาดพร...,2023-08-31
3,21478,6305c503713e23001a6a67b3,6305c4af713e23001a6a67af,1 Bedroom,2,Condo,คอนโด,NaN,25.0,989000.0,...,NaN,NaN,NaN,NaN,NaN,2023-05-31 14:30:02,2023-05-31 14:13:32,baania,https://baania.com/th/project/เสนาคิทท์-บางนา-...,2023-08-31
4,11573,unittype_34957,project_5556,บ้านเดี่ยว SB2,1,Detached House,บ้าน,NaN,80.0,2140000.0,...,1.0,1.0,NaN,NaN,NaN,2023-03-23 12:00:05,2023-03-23 11:41:33,baania,https://baania.com/th/project/วี-อไลฟ์-ลำลูกกา...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43958,24030,64a69b679ac98e00137baccc,64a69aa99ac98e00137bacc5,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,80.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-13 18:30:02,2023-07-13 18:08:11,baania,https://baania.com/th/project/พาราวิลล์-7-64a6...,2023-08-31
43959,27439,unittype_13626,project_5336,1 Bedroom,2,Condo,คอนโด,NaN,32.0,1900000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:33:33,2021-07-15 15:18:28,baania,https://baania.com/th/project/เวนโต้-คอนโด-เกษ...,2023-08-31
43960,1780,unittype_5858,project_1921,Delux Type E,2,Condo,คอนโด,NaN,35.0,1870000.0,...,1.0,1.0,NaN,NaN,NaN,2022-10-17 12:00:18,2022-10-17 11:51:21,baania,https://baania.com/th/project/ริเวนเดลล์-แอปโซ...,2023-08-31
43961,19135,60c0850ce5834700138692ac,project_13885,1 Bedroom Plus,2,Condo,คอนโด,NaN,30.5,2490000.0,...,NaN,NaN,NaN,NaN,1.0,2023-06-12 14:30:03,2023-06-12 14:15:31,baania,https://baania.com/th/project/เคนซิงตัน-สุขุมว...,2023-08-31
43962,19345,611648931685a90014c6a31a,6116457423a53800153ef0f3,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,NaN,200.0,13000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-08-16 15:30:03,2021-08-13 17:38:01,baania,https://baania.com/th/project/บ้านกฤษดานคร-21-...,2023-08-31

In [ ]:
unit_type_data.shape

(43963, 28)

In [ ]:
unit_type_data.columns

Index(['row_number', 'unittype_id', 'project_id', 'name_th', 'propertytype_id',
       'propertytype_name_en', 'propertytype_name_th', 'area_total_min_wa',
       'area_usable_min', 'price_min', 'count_airconditioner',
       'count_elevator', 'count_floor_internal', 'count_parking',
       'count_room_bath', 'count_room_bed', 'count_room_dinning',
       'count_room_guest', 'count_room_kitchen', 'count_room_living',
       'count_room_maid', 'count_room_storage', 'count_room_utility',
       'date_created', 'date_updated', 'source', 'url_unittype', 'day'],
      dtype='object')

# Cleaning Data

## Missing (incomplete) Data

In [ ]:
unit_type_data.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

In [ ]:
# ถ้า drop area_total_min_wa ออก
print(f'{unit_type_data.dropna(subset="area_total_min_wa").shape[0]*100/unit_type_data.shape[0]:.2f}% left')

6.87% left



---

## HW1
เติมพื้นที่บ้านเป็นตารางวาจากพื้นที่ใช้สอยเป็นตรางเมตร เฉพาะข้อมูลคอนโด

เขียนว่า ข้อมูลอสังหา อื่นๆ ควรจะเติมพื้นที่บ้านยังไง

In [ ]:
unit_type_data.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,4441,unittype_11075,project_3853,4 Bedroom,2,Condo,คอนโด,NaN,250.0,50200000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:56,2020-10-14 00:57:57,baania,https://baania.com/th/project/โดมัส-16-3853/4-...,2023-08-31
1,28021,unittype_18174,project_7334,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,132.0,3666666.0,...,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:37:28,2020-10-14 00:43:47,baania,https://baania.com/th/project/บ้านเมฆธารา-2-73...,2023-08-31
2,14541,unittype_35595,project_15267,1 Bedroom,2,Condo,คอนโด,NaN,45.0,3250000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:30,2020-10-14 00:55:24,baania,https://baania.com/th/project/เดอะ-เซสท์-ลาดพร...,2023-08-31
3,21478,6305c503713e23001a6a67b3,6305c4af713e23001a6a67af,1 Bedroom,2,Condo,คอนโด,NaN,25.0,989000.0,...,NaN,NaN,NaN,NaN,NaN,2023-05-31 14:30:02,2023-05-31 14:13:32,baania,https://baania.com/th/project/เสนาคิทท์-บางนา-...,2023-08-31
4,11573,unittype_34957,project_5556,บ้านเดี่ยว SB2,1,Detached House,บ้าน,NaN,80.0,2140000.0,...,1.0,1.0,NaN,NaN,NaN,2023-03-23 12:00:05,2023-03-23 11:41:33,baania,https://baania.com/th/project/วี-อไลฟ์-ลำลูกกา...,2023-08-31

In [ ]:
# Display unique values of 'propertytype_name_en'
print(unit_type_data['propertytype_name_en'].unique())

['Condo' 'Townhome' 'Detached House' 'Twin house' 'Apartment'
 'Home office' 'Commercial' 'Hotel' 'Warehouse / Factory' 'Land'
 'Office Space']

In [ ]:
# prompt: เติมค่า area_total_min_wa ของ propertytype_name_en ที่เป็น 'Condo' โดยแปลงค่าของ area_usable_min ซึ่งมีหน่วยเป็นตารางเมตรอยากเปลี่ยนเป็นตารางวาแล้วเอาค่าไปใส่ที่  area_total_min_wa

# Calculate area_total_min_wa for 'Condo' property types
unit_type_data['area_total_min_wa'] = np.where(
    unit_type_data['propertytype_name_en'] == 'Condo',
    unit_type_data['area_usable_min'] / 3.978,  # Convert sq meters to sq wah  1 ตร.ม. = 3.978 ตร.ว.
    unit_type_data['area_total_min_wa']
)

In [ ]:
unit_type_data

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,4441,unittype_11075,project_3853,4 Bedroom,2,Condo,คอนโด,62.845651,250.0,50200000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:56,2020-10-14 00:57:57,baania,https://baania.com/th/project/โดมัส-16-3853/4-...,2023-08-31
1,28021,unittype_18174,project_7334,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,132.0,3666666.0,...,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:37:28,2020-10-14 00:43:47,baania,https://baania.com/th/project/บ้านเมฆธารา-2-73...,2023-08-31
2,14541,unittype_35595,project_15267,1 Bedroom,2,Condo,คอนโด,11.312217,45.0,3250000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:30,2020-10-14 00:55:24,baania,https://baania.com/th/project/เดอะ-เซสท์-ลาดพร...,2023-08-31
3,21478,6305c503713e23001a6a67b3,6305c4af713e23001a6a67af,1 Bedroom,2,Condo,คอนโด,6.284565,25.0,989000.0,...,NaN,NaN,NaN,NaN,NaN,2023-05-31 14:30:02,2023-05-31 14:13:32,baania,https://baania.com/th/project/เสนาคิทท์-บางนา-...,2023-08-31
4,11573,unittype_34957,project_5556,บ้านเดี่ยว SB2,1,Detached House,บ้าน,NaN,80.0,2140000.0,...,1.0,1.0,NaN,NaN,NaN,2023-03-23 12:00:05,2023-03-23 11:41:33,baania,https://baania.com/th/project/วี-อไลฟ์-ลำลูกกา...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43958,24030,64a69b679ac98e00137baccc,64a69aa99ac98e00137bacc5,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,80.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-13 18:30:02,2023-07-13 18:08:11,baania,https://baania.com/th/project/พาราวิลล์-7-64a6...,2023-08-31
43959,27439,unittype_13626,project_5336,1 Bedroom,2,Condo,คอนโด,8.044243,32.0,1900000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:33:33,2021-07-15 15:18:28,baania,https://baania.com/th/project/เวนโต้-คอนโด-เกษ...,2023-08-31
43960,1780,unittype_5858,project_1921,Delux Type E,2,Condo,คอนโด,8.798391,35.0,1870000.0,...,1.0,1.0,NaN,NaN,NaN,2022-10-17 12:00:18,2022-10-17 11:51:21,baania,https://baania.com/th/project/ริเวนเดลล์-แอปโซ...,2023-08-31
43961,19135,60c0850ce5834700138692ac,project_13885,1 Bedroom Plus,2,Condo,คอนโด,7.667169,30.5,2490000.0,...,NaN,NaN,NaN,NaN,1.0,2023-06-12 14:30:03,2023-06-12 14:15:31,baania,https://baania.com/th/project/เคนซิงตัน-สุขุมว...,2023-08-31
43962,19345,611648931685a90014c6a31a,6116457423a53800153ef0f3,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,NaN,200.0,13000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-08-16 15:30:03,2021-08-13 17:38:01,baania,https://baania.com/th/project/บ้านกฤษดานคร-21-...,2023-08-31

> เขียนว่า ข้อมูลอสังหา อื่นๆ ควรจะเติมพื้นที่บ้านยังไง

**ตอบ**

 ประเภทอสังหา มีดังนี้ ['Condo' 'Townhome' 'Detached House' 'Twin house' 'Apartment'
 'Home office' 'Commercial' 'Hotel' 'Warehouse / Factory' 'Land'
 'Office Space']
 * แบ่งกลุ่มการจัดการตามแต่ละประเภทบ้านก่อน
 * เช็คค่าของแต่ละประเภทว่า area_total_min_wa ว่างทุกค่าเลยไหมหรือแค่บางค่า
     * ถ้าว่างแค่บางค่า (มีอันที่ค่าครบทุกตัวแปร) จะยึดค่าของแถวนั้นมาใช้เทียบบัญญัติไตรยางค์ของค่าว่างในแถวอื่น
     * ถ้าว่างทั้งหมด เช่น Apartment หรือ Condo จะใช้วิธีแปลงหน่วยจาก area_usable_min	(ตารางเมตร) ให้เป็น (ตารางวา) แล้วนำค่าไปเติมใน area_total_min_wa ที่ว่าง

#### ทด

> Townhome

* เช็คก่อนว่ามีตัวไหนที่ area_total_min_wa ว่าไม่ว่าง

In [ ]:
# prompt: ดู area_total_min_wa ของ 'propertytype_name_en' == 'Townhome'

# Display area_total_min_wa for 'Townhome' property types
print(unit_type_data[unit_type_data['propertytype_name_en'] == 'Townhome']['area_total_min_wa'])

1         NaN
11        NaN
16        NaN
18        NaN
24        NaN
         ...
43923     NaN
43929     NaN
43937     NaN
43941     NaN
43951    19.0
Name: area_total_min_wa, Length: 8611, dtype: float64

In [ ]:
# Display rows where 'propertytype_name_en' is 'Townhome'
unit_type_data[unit_type_data['propertytype_name_en'] == 'Townhome']

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
1,28021,unittype_18174,project_7334,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,132.0,3666666.0,...,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:37:28,2020-10-14 00:43:47,baania,https://baania.com/th/project/บ้านเมฆธารา-2-73...,2023-08-31
11,6339,unittype_23196,project_9266,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,207.0,2800000.0,...,1.0,NaN,NaN,NaN,NaN,2022-10-19 14:00:08,2022-10-19 13:37:12,baania,https://baania.com/th/project/บ้านสวนริมคลอง-บ...,2023-08-31
16,32346,unittype_34035,project_14603,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:38:54,2020-10-14 00:52:55,baania,https://baania.com/th/project/เพชรนิรันดร์-วิล...,2023-08-31
18,23757,64745ceee54ccc00137a73e1,64745a08e54ccc00137a73da,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,180.0,2590000.0,...,1.0,NaN,NaN,NaN,NaN,2023-05-29 15:30:03,2023-05-29 15:06:13,baania,https://baania.com/th/project/เซนสิริ-ซิตี้-แห...,2023-08-31
24,17304,5e9434f29f161600121b5473,5e9432269f161600121b546a,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-06-22 16:00:05,2023-06-22 15:57:36,baania,https://baania.com/th/project/ริวโอ-วิลเลจ-3-แ...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43923,34427,unittype_29187,project_12035,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,192.0,3290000.0,...,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:42:07,2020-10-14 19:00:56,baania,https://baania.com/th/project/รัตนาวลัย-12035/...,2023-08-31
43929,33726,unittype_33323,project_14246,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,180.0,2890000.0,...,NaN,NaN,NaN,NaN,NaN,2022-02-04 17:30:03,2022-02-04 17:06:04,baania,https://baania.com/th/project/สมาร์ท-วิลล่า-14...,2023-08-31
43937,27279,unittype_15693,project_6133,ทาวน์โฮมชั้นเดียว,3,Townhome,ทาวน์โฮม,NaN,90.0,500000.0,...,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:37:03,2020-10-14 00:41:03,baania,https://baania.com/th/project/บ้านชวนอยู่-6133...,2023-08-31
43941,25077,unittype_12601,project_4784,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,121.0,1990000.0,...,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:37:58,2020-10-14 00:47:11,baania,https://baania.com/th/project/ซื่อตรง-การ์เด้น...,2023-08-31
43951,14063,unittype_24984,project_9971,ทาวน์โฮมสองชั้น Type A,3,Townhome,ทาวน์โฮม,19.0,150.0,2090000.0,...,1.0,1.0,NaN,1.0,NaN,2023-06-14 11:30:03,2023-06-14 11:06:22,baania,https://baania.com/th/project/สิปัญ-วิลล์-9971...,2023-08-31

In [ ]:
# prompt: ดูค่าของ 'propertytype_name_en' == 'Townhome' ตัวสุดท้าย เอามาทั้งแถว

# Display the last row where 'propertytype_name_en' is 'Townhome'
unit_type_data[unit_type_data['propertytype_name_en'] == 'Townhome'].tail(1)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
43951,14063,unittype_24984,project_9971,ทาวน์โฮมสองชั้น Type A,3,Townhome,ทาวน์โฮม,19.0,150.0,2090000.0,...,1.0,1.0,NaN,1.0,NaN,2023-06-14 11:30:03,2023-06-14 11:06:22,baania,https://baania.com/th/project/สิปัญ-วิลล์-9971...,2023-08-31

* Townhome: จะเห็นว่ามีตัวสุดท้ายของ Townhome ที่มีค่า area_total_min_wa จึงจะใช้วิธีเทียบบัญญัติไตรยางค์ ก็คือ ที่ค่า area_usable_min = 150.0 จะมีค่า area_total_min_wa = 19.0 เราก็จะเอาไปเทียบกับค่าอื่นของ Townhome

> Detached House

In [ ]:
unit_type_data[unit_type_data['propertytype_name_en'] == 'Detached House']

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
4,11573,unittype_34957,project_5556,บ้านเดี่ยว SB2,1,Detached House,บ้าน,NaN,80.0,2140000.0,...,1.0,1.0,NaN,NaN,NaN,2023-03-23 12:00:05,2023-03-23 11:41:33,baania,https://baania.com/th/project/วี-อไลฟ์-ลำลูกกา...,2023-08-31
5,8741,unittype_1672,project_868,บ้านธารธารา,1,Detached House,บ้าน,47.0,80.0,3300000.0,...,1.0,NaN,NaN,NaN,NaN,2022-01-28 11:30:04,2022-01-28 11:27:16,baania,https://baania.com/th/project/สมหวังพร็อพเพอร์...,2023-08-31
8,22086,636a018fcb899000122286c2,project_11863,ออมทรัพย์,1,Detached House,บ้าน,NaN,107.7,2490000.0,...,NaN,NaN,NaN,NaN,NaN,2023-07-31 09:00:05,2023-07-31 08:50:01,baania,https://baania.com/th/project/ปริม-สุวินทวงศ์-...,2023-08-31
10,36966,unittype_5801,project_1908,The Hutch+,1,Detached House,บ้าน,NaN,143.0,3490000.0,...,1.0,NaN,NaN,1.0,NaN,2022-02-24 15:30:06,2022-02-24 15:13:33,baania,https://baania.com/th/project/พิมานเพลส-วงแหวน...,2023-08-31
12,21785,632d2733ea1add001a549518,632d26caea1add001a54950e,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,NaN,2590000.0,...,NaN,NaN,NaN,NaN,NaN,2022-09-23 13:00:04,2022-09-23 11:21:56,baania,https://baania.com/th/project/กรีนโฮม-พูลวิลล่...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43953,24890,unittype_13407,project_2297,Denica,1,Detached House,บ้าน,NaN,146.0,5250000.0,...,1.0,1.0,NaN,NaN,NaN,2023-02-09 18:30:02,2023-02-09 17:55:22,baania,https://baania.com/th/project/เพอร์เฟค-พาร์ค-พ...,2023-08-31
43954,15705,unittype_39613,project_17292,Pine,1,Detached House,บ้าน,NaN,214.0,6590000.0,...,1.0,1.0,NaN,1.0,NaN,2023-01-20 20:00:05,2023-01-20 19:36:18,baania,https://baania.com/th/project/เวนิว-เวสต์เกต-1...,2023-08-31
43957,42127,5f34ea93c801fb0019dacc01,5f34e60ec801fb0019dacbd6,บ้านเดี่ยวชั้น,1,Detached House,บ้าน,NaN,150.0,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2022-08-02 13:30:04,2022-08-02 13:07:41,baania,https://baania.com/th/project/ธาราวิลล์เพชบุระ...,2023-08-31
43958,24030,64a69b679ac98e00137baccc,64a69aa99ac98e00137bacc5,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,80.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-13 18:30:02,2023-07-13 18:08:11,baania,https://baania.com/th/project/พาราวิลล์-7-64a6...,2023-08-31
43962,19345,611648931685a90014c6a31a,6116457423a53800153ef0f3,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,NaN,200.0,13000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-08-16 15:30:03,2021-08-13 17:38:01,baania,https://baania.com/th/project/บ้านกฤษดานคร-21-...,2023-08-31

* Detached House: จะเห็นว่ามีตัวสุดท้ายของ Detached House ที่มีค่า area_total_min_wa จึงจะใช้วิธีเทียบบัญญัติไตรยางค์ ก็คือ ที่ค่า area_usable_min = 80.0 จะมีค่า area_total_min_wa = 47.0 เราก็จะเอาไปเทียบกับค่าอื่นของ Detached House

> Twin house

In [ ]:
unit_type_data[unit_type_data['propertytype_name_en'] == 'Twin house']

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
6,13078,unittype_31787,project_13423,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,144.0,4700000.0,...,1.0,NaN,NaN,1.0,NaN,2022-03-21 14:00:06,2022-03-21 13:41:50,baania,https://baania.com/th/project/ภูเก็ตวิลล่า-กะท...,2023-08-31
14,25471,unittype_16088,project_6304,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,170.0,4750000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:42:38,2020-10-14 19:45:47,baania,https://baania.com/th/project/บ้านศิรินโฮม-630...,2023-08-31
34,37815,unittype_35524,project_15234,บ้านแฝดชั้นเดียว,20000,Twin house,บ้านแฝด,NaN,98.0,1690000.0,...,NaN,NaN,NaN,NaN,NaN,2022-03-07 16:30:06,2022-03-07 16:25:30,baania,https://baania.com/th/project/เปี่ยมสิริ-โชคชั...,2023-08-31
37,17514,5e9d29669f161600121b603d,5e9d28b59f161600121b6039,บ้านแฝดชั้นเดียว,20000,Twin house,บ้านแฝด,NaN,70.0,1590000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:18:14,2020-04-20 12:05:55,baania,https://baania.com/th/project/ท่าศาลาวิลเลจ-2-...,2023-08-31
43,18141,5ec2024e84c1860019f32593,5ec1ff7c84c1860019f32584,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,134.0,2849990.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:28:17,2021-01-12 15:33:25,baania,https://baania.com/th/project/เดอะทัชเฮ้าส์-พห...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43883,22267,6385b98413f8b50012598f52,project_15008,The Star,20000,Twin house,บ้านแฝด,NaN,138.0,3790000.0,...,NaN,NaN,NaN,NaN,NaN,2022-11-29 15:00:04,2022-11-29 14:50:02,baania,https://baania.com/th/project/เดอะ-แพลนท์-ปิ่น...,2023-08-31
43902,24137,64b7e65b5197a70013a9c5bb,641d6aacfecf230013348edd,ศุภการิน,20000,Twin house,บ้านแฝด,NaN,176.0,5890000.0,...,1.0,NaN,NaN,NaN,NaN,2023-07-19 21:30:03,2023-07-19 20:34:27,baania,https://baania.com/th/project/ศุภาลัย-วิลล์-ปิ...,2023-08-31
43906,14487,unittype_30088,project_12652,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,180.0,2500000.0,...,1.0,1.0,NaN,2.0,NaN,2021-09-15 12:00:07,2021-09-15 10:15:19,baania,https://baania.com/th/project/บ้านพฤกษา-33-บาง...,2023-08-31
43918,22630,63c7a53d7866db00121113ce,63c7a4c37866db00121113ca,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,140.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-01-18 15:00:05,2023-01-18 14:53:26,baania,https://baania.com/th/project/บ้านรังสิยา-อุดม...,2023-08-31
43942,14663,unittype_29186,project_11898,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,190.0,3500000.0,...,NaN,1.0,NaN,NaN,NaN,2023-02-02 20:30:02,2023-02-02 20:17:24,baania,https://baania.com/th/project/โชคชัยปัญจทรัพย์...,2023-08-31

In [ ]:
# prompt: หาค่าของ area_total_min_wa ของ 'Twin house' ที่ไม่เป็นค่าว่าง

# Filter for 'Twin house' property types and non-missing 'area_total_min_wa' values
twin_house_data = unit_type_data[
    (unit_type_data['propertytype_name_en'] == 'Twin house') &
    (unit_type_data['area_total_min_wa'].notnull())
]

# Display the 'area_total_min_wa' values
twin_house_data

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
149,12202,unittype_35529,project_15237,บ้านแฝดชั้นเดียว,20000,Twin house,บ้านแฝด,35.0,77.0,1480000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:18:10,2020-04-13 17:33:36,baania,https://baania.com/th/project/เจริญทรัพย์-โมเด...,2023-08-31
576,37292,unittype_36003,project_15426,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,35.0,170.0,3390000.0,...,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:26:58,2021-01-06 15:53:10,baania,https://baania.com/th/project/เดอะริช-ทาวน์-3-...,2023-08-31
928,32718,unittype_37079,project_16048,บ้านแฝดสองชั้น Type A,20000,Twin house,บ้านแฝด,35.0,154.0,4890000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:24:09,2020-10-14 22:35:51,baania,https://baania.com/th/project/ออรา-รามคำแหง-94...,2023-08-31
1426,39091,unittype_38634,project_16906,บ้านแฝดชั้นเดียว,20000,Twin house,บ้านแฝด,37.0,62.0,1750000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:18:11,2020-04-13 17:33:36,baania,https://baania.com/th/project/เดอะทาวน์-รัตภูม...,2023-08-31
2283,33958,unittype_29295,project_12109,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,38.5,114.0,4700000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:22:39,2020-10-14 19:04:02,baania,https://baania.com/th/project/ศุภาลัย-วิลล์-หล...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41679,37284,unittype_34540,project_14874,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,35.0,150.0,2800000.0,...,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:27:25,2021-01-07 10:59:08,baania,https://baania.com/th/project/เค-ทเวนตี้โฟร์-ว...,2023-08-31
41690,38020,unittype_24055,project_9605,บ้านแฝดสองชั้น (ขายแล้ว),20000,Twin house,บ้านแฝด,65.7,146.0,4427980.0,...,NaN,1.0,NaN,NaN,NaN,2021-11-12 13:22:52,2020-10-14 20:14:54,baania,https://baania.com/th/project/123-เรสซิเดนซ์-ศ...,2023-08-31
41835,8739,unittype_2856,project_762,บ้านแฝด,20000,Twin house,บ้านแฝด,24.0,160.0,1790000.0,...,1.0,1.0,NaN,NaN,NaN,2022-10-14 12:30:03,2022-10-14 12:00:13,baania,https://baania.com/th/project/ชลประทานแลนด์โฮม...,2023-08-31
42013,37206,unittype_31158,project_13120,บ้านแฝดชั้นเดียว,20000,Twin house,บ้านแฝด,50.0,100.0,1850000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:18:11,2020-04-13 17:33:36,baania,https://baania.com/th/project/บ้านในสวน-13120/...,2023-08-31
42501,6007,unittype_22559,project_9120,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,35.0,138.0,2890000.0,...,NaN,1.0,NaN,1.0,NaN,2021-11-12 13:19:53,2020-10-14 00:44:24,baania,https://baania.com/th/project/ดิ-เอ็นเทอร์-ทูเ...,2023-08-31

In [ ]:
# Filter for 'Twin house' property types and non-missing 'area_total_min_wa' values
Apartment_data = unit_type_data[
    (unit_type_data['propertytype_name_en'] == 'Apartment') &
    (unit_type_data['area_total_min_wa'].notnull())
]

# Display the 'area_total_min_wa' values
Apartment_data

Empty DataFrame
Columns: [row_number, unittype_id, project_id, name_th, propertytype_id, propertytype_name_en, propertytype_name_th, area_total_min_wa, area_usable_min, price_min, count_airconditioner, count_elevator, count_floor_internal, count_parking, count_room_bath, count_room_bed, count_room_dinning, count_room_guest, count_room_kitchen, count_room_living, count_room_maid, count_room_storage, count_room_utility, date_created, date_updated, source, url_unittype, day]
Index: []

[0 rows x 28 columns]

In [ ]:
# Filter for 'Twin house' property types and non-missing 'area_total_min_wa' values
Homeoffice_data = unit_type_data[
    (unit_type_data['propertytype_name_en'] == 'Home office') &
    (unit_type_data['area_total_min_wa'].notnull())
]

# Display the 'area_total_min_wa' values
Homeoffice_data

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
1994,29454,unittype_31334,project_13199,โฮมออฟฟิศสามชั้น,6,Home office,โฮมออฟฟิศ,20.00,165.0,5090000.0,...,NaN,NaN,NaN,1.0,NaN,2022-03-15 11:30:04,2022-03-15 11:15:38,baania,https://baania.com/th/project/สุพิชฌาย์-ชิโน-เ...,2023-08-31
2478,13010,unittype_30746,project_12983,โฮมออฟฟิศสามชั้น,6,Home office,โฮมออฟฟิศ,25.00,180.0,3300000.0,...,NaN,NaN,NaN,NaN,NaN,2022-08-18 14:30:03,2022-08-18 13:54:45,baania,https://baania.com/th/project/เดอะโฮมวิลล์-129...,2023-08-31
3603,34863,unittype_29747,project_12415,โฮมออฟฟิศสี่ชั้น,6,Home office,โฮมออฟฟิศ,27.00,242.0,7000000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:22:54,2020-10-14 20:18:42,baania,https://baania.com/th/project/บิซทาวน์-ศรีนคริ...,2023-08-31
5260,13861,unittype_24979,project_9971,โฮมออฟฟิศสองชั้น,6,Home office,โฮมออฟฟิศ,25.65,167.0,NaN,...,1.0,NaN,NaN,NaN,NaN,2023-06-14 11:30:03,2023-06-14 11:06:22,baania,https://baania.com/th/project/สิปัญ-วิลล์-9971...,2023-08-31
7775,13451,unittype_8100,project_2724,Type C,6,Home office,โฮมออฟฟิศ,19.00,240.0,9000000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:33:54,2021-09-27 11:01:22,baania,https://baania.com/th/project/ชิค-โฮม-ออฟฟิศ-2...,2023-08-31
7810,37077,unittype_30976,project_13044,โฮมออฟฟิตสามชั้น,6,Home office,โฮมออฟฟิศ,17.00,172.0,5500000.0,...,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:18:05,2020-04-02 12:03:35,baania,https://baania.com/th/project/แลนด์มาร์ค-ซิตี้...,2023-08-31
14518,13450,unittype_8098,project_2724,Type A,6,Home office,โฮมออฟฟิศ,21.00,270.0,9550000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:33:54,2021-09-27 11:01:22,baania,https://baania.com/th/project/ชิค-โฮม-ออฟฟิศ-2...,2023-08-31
14586,39192,unittype_38164,project_16749,โฮมออฟฟิศห้าชั้น,6,Home office,โฮมออฟฟิศ,36.00,450.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:33:28,2021-07-15 15:04:18,baania,https://baania.com/th/project/พรีเมี่ยมเพลส-เก...,2023-08-31
15631,12588,unittype_35672,project_15292,โฮมออฟฟิศห้าชั้น Type A,6,Home office,โฮมออฟฟิศ,39.00,570.0,28000000.0,...,NaN,NaN,NaN,NaN,NaN,2022-12-01 15:00:04,2022-12-01 14:59:43,baania,https://baania.com/th/project/เดอะ-ควอเทียร์-ร...,2023-08-31
16817,33733,unittype_38163,project_16749,โฮมออฟฟิศสี่ชั้น,6,Home office,โฮมออฟฟิศ,24.00,250.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:33:28,2021-07-15 15:04:18,baania,https://baania.com/th/project/พรีเมี่ยมเพลส-เก...,2023-08-31
20476,34927,unittype_29739,project_12407,โฮมออฟฟิตสี่ชั้น,6,Home office,โฮมออฟฟิศ,24.00,260.0,12500000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:22:54,2020-10-14 20:18:39,baania,https://baania.com/th/project/บิซทาวน์-ลาดพร้า...,2023-08-31
20532,12977,unittype_21724,project_8644,Type B,6,Home office,โฮมออฟฟิศ,44.50,323.0,3900000.0,...,NaN,1.0,NaN,NaN,NaN,2021-11-12 13:30:15,2021-02-05 10:54:57,baania,https://baania.com/th/project/เวร่า-บิสเน็ท-ร่...,2023-08-31
21013,38430,unittype_20986,project_3607,โฮมออฟฟิศสามชั้น,6,Home office,โฮมออฟฟิศ,73.60,201.0,9200000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:23:08,2020-10-14 20:34:45,baania,https://baania.com/th/project/รังสิต-บิซ-พาร์ค...,2023-08-31
21363,28110,unittype_7884,project_2667,Tower,6,Home office,โฮมออฟฟิศ,38.00,410.0,22000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:47,2020-10-14 00:56:57,baania,https://baania.com/th/project/เดอะ-ไพรมารี-101...,2023-08-31
23924,30471,unittype_31036,project_13077,โฮมออฟฟิศสองชั้น,6,Home office,โฮมออฟฟิศ,18.00,120.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:25,2020-10-14 01:10:08,baania,https://baania.com/th/project/พารากอน-เซ็นทรัล...,2023-08-31
23930,36504,unittype_38439,project_16857,โฮมออฟฟิศ,6,Home office,โฮมออฟฟิศ,21.00,150.0,2590000.0,...,NaN,NaN,NaN,NaN,NaN,2022-03-10 14:30:04,2022-03-10 14:29:03,baania,https://baania.com/th/project/สุรนารีวิลล์-บ้า...,2023-08-31
26106,3417,unittype_7980,project_2667,Loft,6,Home office,โฮมออฟฟิศ,22.00,270.0,10500000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:47,2020-10-14 00:56:57,baania,https://baania.com/th/project/เดอะ-ไพรมารี-101...,2023-08-31
26964,12978,unittype_22803,project_8644,Type C,6,Home office,โฮมออฟฟิศ,22.80,215.0,4990000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:30:15,2021-02-05 10:54:57,baania,https://baania.com/th/project/เวร่า-บิสเน็ท-ร่...,2023-08-31
27810,12865,unittype_24374,project_9737,โฮมออฟฟิศสามชั้น,6,Home office,โฮมออฟฟิศ,18.40,186.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:19:28,2020-10-14 00:37:24,baania,https://baania.com/th/project/ดิ-เอพริล-เรสท์ฟ...,2023-08-31
31939,37182,unittype_31021,project_13068,โฮมออฟฟิศสามชั้น,6,Home office,โฮมออฟฟิศ,23.30,230.0,3500000.0,...,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:29:19,2021-01-25 11:38:18,baania,https://baania.com/th/project/แลนด์มาร์ค-ไลฟ์-...,2023-08-31
32718,33048,unittype_37461,project_16303,โฮมออฟฟิตสี่ชั้น,6,Home office,โฮมออฟฟิศ,22.00,295.0,9500000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:59,2020-10-14 20:26:46,baania,https://baania.com/th/project/เมสโต้-เกษตร-นวม...,2023-08-31
33215,40587,unittype_26685,project_10745,โฮมออฟฟิศสามชั้น,6,Home office,โฮมออฟฟิศ,31.50,174.0,2890000.0,...,1.0,1.0,NaN,NaN,NaN,2022-08-11 14:30:06,2022-08-11 14:03:57,baania,https://baania.com/th/project/บ้านธัญธร-10745/...,2023-08-31
34588,34607,unittype_31033,project_13068,โฮมออฟฟิศสองชั้น,6,Home office,โฮมออฟฟิศ,22.30,143.0,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:29:19,2021-01-25 11:38:18,baania,https://baania.com/th/project/แลนด์มาร์ค-ไลฟ์-...,2023-08-31
38509,15473,unittype_39644,project_17306,โฮมออฟฟิศสี่ชั้น,6,Home office,โฮมออฟฟิศ,22.00,250.0,8150000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:31:52,2021-05-17 17:12:08,baania,https://baania.com/th/project/เดอะวัน-บางนา-17...,2023-08-31
38939,41199,unittype_39242,project_17135,โฮมออฟฟิตสามชั้น,6,Home office,โฮมออฟฟิศ,20.00,171.0,4490000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:23:01,2020-10-14 20:29:41,baania,https://baania.com/th/project/อารียา-บริกก์-ดอ...,2023-08-31
39768,13452,unittype_8099,project_2724,Type B,6,Home office,โฮมออฟฟิศ,20.00,250.0,10000000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:33:54,2021-09-27 11:01:22,baania,https://baania.com/th/project/ชิค-โฮม-ออฟฟิศ-2...,2023-08-31
40467,34603,unittype_30994,project_13053,โฮมออฟฟิศสองชั้น,6,Home office,โฮมออฟฟิศ,19.00,120.0,1990000.0,...,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:29:18,2021-01-25 11:33:45,baania,https://baania.com/th/project/บ้านสวยธานี-1305...,2023-08-31
41511,2914,unittype_7964,project_2664,โฮมออฟฟิตสามชั้น,6,Home office,โฮมออฟฟิศ,24.00,155.0,4500000.0,...,2.0,NaN,NaN,NaN,NaN,2021-11-12 13:20:46,2020-10-14 00:56:56,baania,https://baania.com/th/project/เดอะ-คอนเนค-พัฒน...,2023-08-31
42776,12979,unittype_22804,project_8644,Type D-1,6,Home office,โฮมออฟฟิศ,21.10,169.0,8700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:30:15,2021-02-05 10:54:57,baania,https://baania.com/th/project/เวร่า-บิสเน็ท-ร่...,2023-08-31
42920,30700,unittype_32309,project_13593,โฮมออฟฟิศสามชั้น,6,Home office,โฮมออฟฟิศ,22.00,146.0,2990000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:28,2020-10-14 01:10:30,baania,https://baania.com/th/project/ภูเก็ตโกลเด้นวิล...,2023-08-31
43424,9757,unittype_27486,project_11160,โฮมออฟฟิศห้าชั้น,6,Home office,โฮมออฟฟิศ,17.60,250.0,5500000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:22,2020-10-14 01:09:48,baania,https://baania.com/th/project/โฮมออฟฟิศใกล้มหา...,2023-08-31

In [ ]:
# Filter for 'Twin house' property types and non-missing 'area_total_min_wa' values
Commercial_data = unit_type_data[
    (unit_type_data['propertytype_name_en'] == 'Commercial') &
    (unit_type_data['area_total_min_wa'].notnull())
]

# Display the 'area_total_min_wa' values
Commercial_data

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
70,37485,unittype_23888,project_9538,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,21.40,144.0,4590000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:33:10,2021-07-05 12:08:25,baania,https://baania.com/th/project/คริสตัล-ทาวน์-95...,2023-08-31
201,36211,unittype_23701,project_9466,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,19.50,NaN,2290000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:33:10,2021-07-05 12:08:30,baania,https://baania.com/th/project/อีสเทิร์น-แลนด์ซ...,2023-08-31
854,31699,unittype_21383,project_8390,อาคารพาณิชย์สี่ชั้น,4,Commercial,อาคารพาณิชย์,34.00,280.0,6400000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:19:31,2020-10-14 00:38:09,baania,https://baania.com/th/project/บุษราคัม-เทอเรซ-...,2023-08-31
1321,35067,unittype_33568,project_14373,อาคารพาณิชย์สองชั้น,4,Commercial,อาคารพาณิชย์,22.80,120.0,2400000.0,...,1.0,NaN,NaN,1.0,NaN,2022-06-06 15:00:10,2022-06-06 14:58:11,baania,https://baania.com/th/project/ปัณณทรัพย์-ปราณบ...,2023-08-31
1429,11434,unittype_34631,project_14928,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,21.37,260.0,3650000.0,...,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:27:27,2021-01-07 11:15:12,baania,https://baania.com/th/project/ไลฟ์บิส-2-14928/...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42566,37388,unittype_33834,project_14497,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,19.00,250.0,5400000.0,...,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:18:07,2020-04-03 11:32:07,baania,https://baania.com/th/project/อาคารพาณิชย์-ถนน...,2023-08-31
42780,31670,unittype_21770,project_8678,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,18.00,150.0,3200000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:24:24,2020-10-14 23:21:04,baania,https://baania.com/th/project/ร่มทิพย์-ปาร์ค-8...,2023-08-31
43200,29728,unittype_267,project_84,Office Villa Type A,4,Commercial,อาคารพาณิชย์,25.00,205.0,5250000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:25:43,2020-11-17 15:06:51,baania,https://baania.com/th/project/มาลาดา-โฮม-แอนด์...,2023-08-31
43322,31666,unittype_21430,project_8426,อาคารพาณิชย์สามชั้น Type A,4,Commercial,อาคารพาณิชย์,20.10,173.0,3490000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:19:31,2020-10-14 00:38:11,baania,https://baania.com/th/project/บุษบา-โกลเด้นทาว...,2023-08-31
43487,32109,unittype_26400,project_10641,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,18.00,144.0,4190000.0,...,NaN,NaN,NaN,NaN,NaN,2022-10-19 15:00:10,2022-10-19 14:42:33,baania,https://baania.com/th/project/รัตนากรวิลเลจ-25...,2023-08-31



---

In [ ]:
# prompt: Filter for  'Hotel', 'Warehouse / Factory', 'Land' and 'Office Space' property types and non-missing 'area_total_min_wa' values

# Define the property types to filter
property_types = ['Hotel', 'Warehouse / Factory', 'Land', 'Office Space']

# Filter the DataFrame
filtered_data = unit_type_data[
    (unit_type_data['propertytype_name_en'].isin(property_types)) &
    (unit_type_data['area_total_min_wa'].notnull())
]

# Display the filtered data
filtered_data

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
14528,31991,unittype_33694,project_14425,ที่ดินเปล่า,7,Land,ที่ดิน,52.8,NaN,4500000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:55,2020-10-14 20:19:07,baania,https://baania.com/th/project/เดอะไพรม์-ฮอล์ริ...,2023-08-31
33451,14840,unittype_16735,project_4249,ที่ดินเปล่า,7,Land,ที่ดิน,80.0,NaN,3000000.0,...,NaN,NaN,NaN,NaN,NaN,2022-12-19 14:30:02,2022-12-19 14:18:43,baania,https://baania.com/th/project/เนเบอร์โฮม-วัชรพ...,2023-08-31



---

###  5.สร้าง model หาค่าว่าง

In [5]:
unit_type_data

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,4441,unittype_11075,project_3853,4 Bedroom,2,Condo,คอนโด,NaN,250.0,50200000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:56,2020-10-14 00:57:57,baania,https://baania.com/th/project/โดมัส-16-3853/4-...,2023-08-31
1,28021,unittype_18174,project_7334,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,132.0,3666666.0,...,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:37:28,2020-10-14 00:43:47,baania,https://baania.com/th/project/บ้านเมฆธารา-2-73...,2023-08-31
2,14541,unittype_35595,project_15267,1 Bedroom,2,Condo,คอนโด,NaN,45.0,3250000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:30,2020-10-14 00:55:24,baania,https://baania.com/th/project/เดอะ-เซสท์-ลาดพร...,2023-08-31
3,21478,6305c503713e23001a6a67b3,6305c4af713e23001a6a67af,1 Bedroom,2,Condo,คอนโด,NaN,25.0,989000.0,...,NaN,NaN,NaN,NaN,NaN,2023-05-31 14:30:02,2023-05-31 14:13:32,baania,https://baania.com/th/project/เสนาคิทท์-บางนา-...,2023-08-31
4,11573,unittype_34957,project_5556,บ้านเดี่ยว SB2,1,Detached House,บ้าน,NaN,80.0,2140000.0,...,1.0,1.0,NaN,NaN,NaN,2023-03-23 12:00:05,2023-03-23 11:41:33,baania,https://baania.com/th/project/วี-อไลฟ์-ลำลูกกา...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43958,24030,64a69b679ac98e00137baccc,64a69aa99ac98e00137bacc5,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,80.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-13 18:30:02,2023-07-13 18:08:11,baania,https://baania.com/th/project/พาราวิลล์-7-64a6...,2023-08-31
43959,27439,unittype_13626,project_5336,1 Bedroom,2,Condo,คอนโด,NaN,32.0,1900000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:33:33,2021-07-15 15:18:28,baania,https://baania.com/th/project/เวนโต้-คอนโด-เกษ...,2023-08-31
43960,1780,unittype_5858,project_1921,Delux Type E,2,Condo,คอนโด,NaN,35.0,1870000.0,...,1.0,1.0,NaN,NaN,NaN,2022-10-17 12:00:18,2022-10-17 11:51:21,baania,https://baania.com/th/project/ริเวนเดลล์-แอปโซ...,2023-08-31
43961,19135,60c0850ce5834700138692ac,project_13885,1 Bedroom Plus,2,Condo,คอนโด,NaN,30.5,2490000.0,...,NaN,NaN,NaN,NaN,1.0,2023-06-12 14:30:03,2023-06-12 14:15:31,baania,https://baania.com/th/project/เคนซิงตัน-สุขุมว...,2023-08-31
43962,19345,611648931685a90014c6a31a,6116457423a53800153ef0f3,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,NaN,200.0,13000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-08-16 15:30:03,2021-08-13 17:38:01,baania,https://baania.com/th/project/บ้านกฤษดานคร-21-...,2023-08-31

In [6]:
unit_type_data.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

* missing น้อยกว่าไปเติมมากกว่า

หาว่า price_min หรือ count_room_bed มี missing น้อยกว่ากัน

In [7]:
unit_type_data.isnull().sum()

row_number                  0
unittype_id                 0
project_id                  0
name_th                     0
propertytype_id             0
propertytype_name_en        0
propertytype_name_th        0
area_total_min_wa       40941
area_usable_min          5317
price_min                8536
count_airconditioner    42207
count_elevator          43963
count_floor_internal    13045
count_parking           18994
count_room_bath          1627
count_room_bed           1829
count_room_dinning      30536
count_room_guest        31216
count_room_kitchen      23906
count_room_living       33930
count_room_maid         41830
count_room_storage      39949
count_room_utility      43034
date_created                0
date_updated                0
source                      0
url_unittype                0
day                         0
dtype: int64

In [8]:
unit_type_data.isnull()['price_min'].sum()

8536

In [9]:
unit_type_data.isnull()['count_room_bed'].sum()

1829

In [10]:
unit_type_data.isnull()['count_room_bath'].sum()

1627

เราสร้าง model เพื่อทำนายย price_min โดยดูจาก count_room_bed และ count_room_bath

เราเริ่มจาก กำจัดค่า missing ใน count_missing_bed และ count_missing_bath

In [14]:
unit_type_data_drop_bed_bath = unit_type_data.dropna(subset=['count_room_bed', 'count_room_bath'])
unit_type_data_drop_bed_bath.shape

(41985, 28)

In [15]:
unit_type_data_drop_bed_bath.isnull()['price_min'].sum()

7714

แยก data ที่ไม่ missing ออกมาสร้าง model

In [16]:
unit_type_data_drop_bed_bath_not_missing = unit_type_data_drop_bed_bath.dropna(subset=['price_min'])
unit_type_data_drop_bed_bath_not_missing.shape

(34271, 28)

In [18]:
# prompt: create linear regression model to predict price_min from count_room_bed and count_room_bath
# 1.import
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Prepare the data
X = unit_type_data_drop_bed_bath_not_missing[['count_room_bed', 'count_room_bath']]
y = unit_type_data_drop_bed_bath_not_missing['price_min']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #seed เลขเดียวกันสุ่มได้ค่าเดียวกัน

# Create and train the linear regression model
# 2.Define
model = LinearRegression()
# 3.train
model.fit(X_train, y_train) #(feature,predicted)

# Print the coefficients and intercept
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

# Evaluate
from sklearn.metrics import r2_score
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

# 4.predict
y_pred = model.predict(X_test)

Coefficients: [-576330.07381864 4229159.08456289]
Intercept: -2564599.8275842434
R-squared: 0.24786980320017826

* ใช้จริงไม่ได้ R2 น้อยเกิน

มี data ไหนที่ price_min missing ไปบ้าง

In [20]:
missing_row = unit_type_data_drop_bed_bath['price_min'].isnull()
missing_row

0        False
1        False
2        False
3        False
4        False
         ...
43958     True
43959    False
43960    False
43961    False
43962    False
Name: price_min, Length: 41985, dtype: bool

predict ค่าว่างด้วย model


```
y_pred = model.predict(X_test)
```

In [21]:
predicted = model.predict(unit_type_data_drop_bed_bath[missing_row][['count_room_bed', 'count_room_bath']])
predicted

array([ 1088229.18316002,  4741058.19390427, 12623046.28921143, ...,
        4741058.19390427,  1088229.18316002,  4741058.19390427])

เติมค่าว่างด้วยค่าที่ predict ด้วย model

In [22]:
unit_type_data_drop_bed_bath.loc[missing_row, 'price_min'] = predicted

In [23]:
unit_type_data_drop_bed_bath.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min               False
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath         False
count_room_bed          False
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

# ข้อมูลมีความซ้ำซ้อน (Duplicate Data)

## Example

In [29]:
# prompt: เลือกมาเฉพาะข้อมูลบ้านแฝด

# Filter the DataFrame for 'Twin house' property type
twin_houses = unit_type_data[unit_type_data['propertytype_name_en'] == 'Twin house']

# Display the filtered data
twin_houses.shape

(2352, 28)

In [30]:
twin_houses.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
6,13078,unittype_31787,project_13423,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,144.0,4700000.0,...,1.0,NaN,NaN,1.0,NaN,2022-03-21 14:00:06,2022-03-21 13:41:50,baania,https://baania.com/th/project/ภูเก็ตวิลล่า-กะท...,2023-08-31
14,25471,unittype_16088,project_6304,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,170.0,4750000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:42:38,2020-10-14 19:45:47,baania,https://baania.com/th/project/บ้านศิรินโฮม-630...,2023-08-31
34,37815,unittype_35524,project_15234,บ้านแฝดชั้นเดียว,20000,Twin house,บ้านแฝด,NaN,98.0,1690000.0,...,NaN,NaN,NaN,NaN,NaN,2022-03-07 16:30:06,2022-03-07 16:25:30,baania,https://baania.com/th/project/เปี่ยมสิริ-โชคชั...,2023-08-31
37,17514,5e9d29669f161600121b603d,5e9d28b59f161600121b6039,บ้านแฝดชั้นเดียว,20000,Twin house,บ้านแฝด,NaN,70.0,1590000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:18:14,2020-04-20 12:05:55,baania,https://baania.com/th/project/ท่าศาลาวิลเลจ-2-...,2023-08-31
43,18141,5ec2024e84c1860019f32593,5ec1ff7c84c1860019f32584,บ้านแฝดสองชั้น,20000,Twin house,บ้านแฝด,NaN,134.0,2849990.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:28:17,2021-01-12 15:33:25,baania,https://baania.com/th/project/เดอะทัชเฮ้าส์-พห...,2023-08-31

In [31]:
unit_type_data_dup = pd.concat([unit_type_data, twin_houses])

In [32]:
unit_type_data_dup.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
43883     True
43902     True
43906     True
43918     True
43942     True
Length: 46315, dtype: bool

In [ ]:
unit_type_data_dup.drop_duplicates()

# ข้อมูลบางตัวในชุดข้อมูลมีลักษณะผิดปกติหรือแตกต่างจากข้อมูลส่วนใหญ่ (Outlier)

# ค่าตัวแปรบางตัวที่ไม่ถูกต้อง (Erroneous Data)

* ราคาติดลบไหม
* อายุติดลบหรือเปล่า

# ข้อมูลมีค่าตัวแปรไม่สอดคล้องซึ่งกันและกัน (Inconsistent)

* เลือก column ที่เหมาะสม

## Example

เกิดเมื่อรวมข้อมูลจากหลาย ๆ แหล่งแล้ว ค่าใน col ไม่เป็นไปในทิศทางเดียวกัน เช่น column อายุไม่ตรงกับ column วันเกิดหลังจากการคำนวณอายุแล้ว

## Fix

### เลือกเก็บเฉพาะ column ที่ถูกต้องและเหมาะสมที่สุด

# Data Integration (การรวมข้อมูลจากแหล่งข้อมูลหลายๆ แหล่ง)

## 1. รวมแกน Y (add rows - เพิ่ม Data)

เกิดตอนที่ data ที่มีหลายเวอชัน มีหลายๆปี แล้วนำมาต่อกัน

## 2. รวมแกน X (add columns - เพิ่ม feature)

เอาข้อมูลของ project มาใส่เพิ่ม map merge

# Data Reduction (การลดปริมาณข้อมูลในการวิเคราะห์ข้อมูล)

* X - feature
* Y - class(row)

## Reuduce number of data (row-axis) - Sampling

### Sampling แบบกำหนดค่า Seed

In [34]:
unit_type_data.sample(random_state=6) #กำหนด seed อย่างเดียว

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
25260,35735,unittype_30359,project_12826,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,NaN,68.0,3900000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:44:37,2020-10-14 21:43:07,baania,https://baania.com/th/project/บีแอลพลาซ่า-1282...,2023-08-31

### Sampling แบบกำหนดค่า n จำนวน data ที่ถูกสุ่มขึ้นมา

In [35]:
unit_type_data.sample(10, random_state=6) # ได้มากกว่า 1 ค่า

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
25260,35735,unittype_30359,project_12826,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,NaN,68.00,3900000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:44:37,2020-10-14 21:43:07,baania,https://baania.com/th/project/บีแอลพลาซ่า-1282...,2023-08-31
40029,42856,5fa231b0d0235b0019c19605,5fa22fefc7e77400194375bc,AG2,1,Detached House,บ้าน,NaN,101.84,3750000.0,...,1.0,1.0,NaN,1.0,NaN,2022-05-31 14:00:08,2022-05-31 13:46:38,baania,https://baania.com/th/project/อัญชัน-การ์เด้น-...,2023-08-31
15309,8477,unittype_8734,project_2984,1 Bedroom Plus,2,Condo,คอนโด,NaN,31.00,2590000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:20:48,2020-10-14 00:57:13,baania,https://baania.com/th/project/เอชทู-โกลว์-2984...,2023-08-31
40379,25911,unittype_10544,project_3660,ชีวานันท์,1,Detached House,บ้าน,NaN,238.00,5140000.0,...,1.0,1.0,NaN,1.0,NaN,2021-11-12 13:19:39,2020-10-14 00:40:11,baania,https://baania.com/th/project/ชีวารมย์-รังสิต-...,2023-08-31
17397,36540,unittype_16429,project_6477,B(B2),2,Condo,คอนโด,NaN,25.00,2190000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:31:06,2021-03-18 15:26:42,baania,https://baania.com/th/project/น็อตติ้ง-ฮิลล์-ส...,2023-08-31
32745,11816,unittype_35009,project_15036,3 Bedroom,2,Condo,คอนโด,NaN,146.00,25900000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:28,2020-10-14 00:55:11,baania,https://baania.com/th/project/บ้านสิริ-ทเวนตี้...,2023-08-31
20853,37518,unittype_23708,project_9470,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,50.8,98.00,2300000.0,...,1.0,1.0,NaN,1.0,NaN,2021-11-12 13:28:43,2021-01-13 15:10:06,baania,https://baania.com/th/project/เอสซี-ฮิลล์-2-อี...,2023-08-31
9952,9482,unittype_28255,project_11532,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,95.00,1500000.0,...,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:38:17,2020-10-14 00:49:20,baania,https://baania.com/th/project/บ้านแซมไอซ์วิลล่...,2023-08-31
27605,36142,unittype_2172,project_1097,บ้านรุ่งฤดี,1,Detached House,บ้าน,NaN,152.00,1900000.0,...,1.0,NaN,NaN,NaN,NaN,2022-10-17 12:00:07,2022-10-17 11:32:31,baania,https://baania.com/th/project/บ้านรุ่งอรุณ-3-1...,2023-08-31
5899,3004,unittype_8771,project_2976,Metro,3,Townhome,ทาวน์โฮม,NaN,175.00,4490000.0,...,1.0,1.0,NaN,1.0,NaN,2021-11-12 13:24:13,2020-10-14 22:42:14,baania,https://baania.com/th/project/พาทิโอ-งามวงศ์วา...,2023-08-31

### Sampling แบบกำหนดเป็น %

In [36]:
unit_type_data.sample(frac=0.2, random_state=6) #frac=0.2 ถูกสุ่มมา 20%

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
25260,35735,unittype_30359,project_12826,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,NaN,68.00,3900000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:44:37,2020-10-14 21:43:07,baania,https://baania.com/th/project/บีแอลพลาซ่า-1282...,2023-08-31
40029,42856,5fa231b0d0235b0019c19605,5fa22fefc7e77400194375bc,AG2,1,Detached House,บ้าน,NaN,101.84,3750000.0,...,1.0,1.0,NaN,1.0,NaN,2022-05-31 14:00:08,2022-05-31 13:46:38,baania,https://baania.com/th/project/อัญชัน-การ์เด้น-...,2023-08-31
15309,8477,unittype_8734,project_2984,1 Bedroom Plus,2,Condo,คอนโด,NaN,31.00,2590000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:20:48,2020-10-14 00:57:13,baania,https://baania.com/th/project/เอชทู-โกลว์-2984...,2023-08-31
40379,25911,unittype_10544,project_3660,ชีวานันท์,1,Detached House,บ้าน,NaN,238.00,5140000.0,...,1.0,1.0,NaN,1.0,NaN,2021-11-12 13:19:39,2020-10-14 00:40:11,baania,https://baania.com/th/project/ชีวารมย์-รังสิต-...,2023-08-31
17397,36540,unittype_16429,project_6477,B(B2),2,Condo,คอนโด,NaN,25.00,2190000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:31:06,2021-03-18 15:26:42,baania,https://baania.com/th/project/น็อตติ้ง-ฮิลล์-ส...,2023-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17888,9005,unittype_28015,project_11452,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,120.00,2200000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:20,2020-10-14 00:36:41,baania,https://baania.com/th/project/บ้านชาญสมร-11452...,2023-08-31
10518,15098,unittype_36829,project_15923,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,NaN,180.00,3990000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:21,2020-10-14 00:53:37,baania,https://baania.com/th/project/พาสิริ-ธารา-5-15...,2023-08-31
6364,4842,unittype_16826,project_6679,บ้านเดี่ยวสองชั้น Type A,1,Detached House,บ้าน,NaN,140.00,3100000.0,...,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:37:08,2020-10-14 00:41:36,baania,https://baania.com/th/project/บ้านเมืองเอก-6-6...,2023-08-31
27351,32803,unittype_37293,project_16274,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,NaN,300.00,9550000.0,...,NaN,NaN,NaN,NaN,NaN,2021-07-16 10:30:03,2021-07-16 10:14:56,baania,https://baania.com/th/project/เลคไซค์-คอร์ท-5-...,2023-08-31
21484,21700,6322b1b3ea1add001a548f6a,6322af97ea1add001a548f61,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,NaN,2590000.0,...,NaN,NaN,NaN,NaN,NaN,2022-09-15 12:30:02,2022-09-15 12:03:30,baania,https://baania.com/th/project/คันทรี่ฮิลล์-632...,2023-08-31

### Sampling แบบคืนค่า

In [37]:
sam_no_replc = unit_type_data.sample(frac=0.2, random_state=6)
sam_no_replc.duplicated().any() # ไม่มีซ้ำ เพราะแต่ละตัวมันจับกันแค่รอบเดียว

False

In [38]:
sam_with_replc = unit_type_data.sample(frac=0.2, replace=True, random_state=6)
sam_with_replc.duplicated().any() # Output=True แสดงว่า มีบาง data ที่ถูกสุ่มมา 2 รอบ

True

### Sampling แบบเพิ่มจำนวนข้อมูล

In [39]:
sam_with_replc_120 = unit_type_data.sample(frac=1.2, replace=True, random_state=6)# frac=1.2 --> 120% สุ่มมากกว่าจำนวนที่เป็นต้อง replace=True
sam_with_replc_120.shape

(52756, 28)